# IQ Portal Configuration
# Add your application-specific properties here
askiq.model.base_url=http://iq-agent:8000
askiq.model.api_key={{ .Values.global.iqPlatform.config.askiqApiKey | default "dcHZnqfkrFcFPmXR9_0b1lmRTzhb4BYODymRwVmG0Ow=" }}